CREATE TABLE apartments
(
    id               UUID                        NOT NULL,
    apartment_type   SMALLINT                    NOT NULL,
    ref_id           INTEGER                     NOT NULL,
    address          TEXT                NOT NULL,
    user_address     TEXT                NOT NULL,
    latitude         DOUBLE PRECISION            NOT NULL,
    longitude        DOUBLE PRECISION            NOT NULL,
    amount           DOUBLE PRECISION            NOT NULL,
    currency         VARCHAR(255)                NOT NULL,
    photo            TEXT,
    up_available_in  INTEGER                     NOT NULL,
    url              TEXT                NOT NULL,
    author_id        INTEGER,
    resale           BOOLEAN,
    number_of_rooms  INTEGER,
    floor            INTEGER,
    number_of_floors INTEGER,
    total            DOUBLE PRECISION,
    living           DOUBLE PRECISION,
    kitchen          DOUBLE PRECISION,
    seller_type      VARCHAR(255),
    rent_type        VARCHAR(255),
    owner            BOOLEAN,
    event            SMALLINT                    NOT NULL,
    postcode         INTEGER,
    country          VARCHAR(255),
    neighbourhood    VARCHAR(255),
    county           VARCHAR(255),
    street           VARCHAR(255),
    country_code     VARCHAR(255),
    city             VARCHAR(255),
    district         VARCHAR(255),
    house_number     VARCHAR(255),
    state            VARCHAR(255),
    formatted        TEXT,
    state_code       VARCHAR(255),
    box_lon1         DOUBLE PRECISION,
    box_lat1         DOUBLE PRECISION,
    box_lon2         DOUBLE PRECISION,
    box_lat2         DOUBLE PRECISION,
    geo_data_status  SMALLINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_time_up     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    app_created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_sent_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_apartments PRIMARY KEY (id)
);